# Generated by Django 4.0.5 on 2022-06-13 13:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_object_type', models.CharField(blank=True, choices=[('article', 'Article'), ('website', 'Website')], default='article', max_length=40, verbose_name='Open graph type')),
                ('seo_index', models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'No index')], default='index', max_length=15, verbose_name='Index robots value')),
                ('seo_follow', models.CharField(blank=True, choices=[('follow', 'Follow'), ('nofollow', 'No follow')], default='follow', max_length=15, verbose_name='Follow robots value')),
                ('seo_canonical', models.CharField(blank=True, max_length=255, verbose_name='Canonical')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('seo_og_title', models.CharField(blank=True, max_length=255, verbose_name='OpenGraph Title')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('seo_description', models.TextField(blank=True, verbose_name='Description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='H1 title')),
                ('seo_h2', models.CharField(blank=True, max_length=255, verbose_name='H2 title')),
                ('seo_h3', models.CharField(blank=True, max_length=255, verbose_name='H3 title')),
                ('seo_text', models.TextField(blank=True, help_text='Can be useful for some static pages or some objects (like product category).', verbose_name='Seo text')),
                ('seo_img_width', models.PositiveIntegerField(default=1200, verbose_name='Image width')),
                ('seo_img_height', models.PositiveIntegerField(default=630, verbose_name='Image height')),
                ('seo_img_alt', models.CharField(blank=True, max_length=255, verbose_name='Image alt text')),
                ('title', models.CharField(max_length=200, verbose_name='The title')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='The title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='The title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Post content')),
                ('content_uk', ckeditor.fields.RichTextField(null=True, verbose_name='Post content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Post content')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, verbose_name='Name of post in URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Post`s creator')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Liked post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Like`s owner')),
            ],
        ),
    ]
