# Generated by Django 4.0.5 on 2022-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
